server:
  port: 4004 # Gateway listens on port 4004


auth:
  service:
    url: http://localhost:4005


spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # Route for /api/patients/** to patient-service
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # Route for /api/images/** to image-service
        - id: image-service-route
          uri: http://image-service:4007
          predicates:
            - Path=/api/images/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # Route for /api/billing/** to billing-service
        - id: billing-service-route
          uri: http://billing-service:4001
          predicates:
            - Path=/api/billing/**
          filters:
            - StripPrefix=1
            - JwtValidation
        
        # Route for /api/patients/** to patient-service
        - id: medical-staff-service-route
          uri: http://medical-staff-service:4006
          predicates:
            - Path=/api/medical-staff/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # Route for /api/analytics/** to analytics-service
        - id: analytics-service-route
          uri: http://analytics-service:4002
          predicates:
            - Path=/api/analytics/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # Route for /api/docs/patients to patient-service /v3/api-docs
        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

        - id: api-docs-auth-route
          uri: http://auth-service:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs

        - id: api-docs-analytics-route
          uri: http://analytics-service:4002
          predicates:
            - Path=/api-docs/analytics
          filters:
            - RewritePath=/api-docs/analytics,/v3/api-docs

        - id: api-docs-billing-route
          uri: http://billing-service:4001
          predicates:
            - Path=/api-docs/billing
          filters:
            - RewritePath=/api-docs/billing,/v3/api-docs
        
        - id: api-docs-medical-staff-route
          uri: http://medical-staff-service:4006
          predicates:
            - Path=/api-docs/medical-staff
          filters:
            - RewritePath=/api-docs/medical-staff,/v3/api-docs

        - id: api-docs-image-route
          uri: http://image-service:4007
          predicates:
            - Path=/api-docs/image
          filters:
            - RewritePath=/api-docs/image,/v3/api-docs